bf16: true
cache_dir: ./cache/llama3-8b-it
cutoff_len: 1024
dataset: ultra_combined_fb0.01_ch0.1
do_train: true
eval_strategy: 'no'
finetuning_type: lora
gradient_accumulation_steps: 16
learning_rate: 1.0e-05
logging_steps: 20
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 10000000
model_name_or_path: ./cache/llama3-8b-it
num_train_epochs: 1
output_dir: ./saves/llama3-8b-it/simpo_sft_hybrid
overwrite_cache: true
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
plot_loss: true
pref_beta: 2.0
pref_ftx: 1.0
pref_loss: simpo
preprocessing_num_workers: 12
ref_model: meta-llama/Meta-Llama-3-8B-Instruct
save_steps: 300
simpo_gamma: 2.0
stage: dpo
template: mistral
trust_remote_code: true
val_size: 0.0
warmup_ratio: 0.1
