bf16: true
cache_dir: ./cache/qwen2-7b-it
cutoff_len: 1024
dataset: ultra_combined_fb0.01_ch0.1
do_train: true
eval_strategy: 'no'
finetuning_type: lora
gradient_accumulation_steps: 16
learning_rate: 1.0e-05
logging_steps: 20
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 10000000
model_name_or_path: ./cache/qwen2-7b-it
num_train_epochs: 1
output_dir: ./saves/qwen2-7b-it/dpo_sft_hybrid
overwrite_cache: true
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
plot_loss: true
pref_beta: 0.1
pref_ftx: 1.0
pref_loss: sigmoid
preprocessing_num_workers: 12
ref_model: Qwen/Qwen2-7B-Instruct
save_steps: 300
stage: dpo
template: mistral
trust_remote_code: true
val_size: 0.0
warmup_ratio: 0.1
