stage: dpo
do_train: true
finetuning_type: lora
template: default
cutoff_len: 2048
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 12
num_train_epochs: 3
per_device_train_batch_size: 8
gradient_accumulation_steps: 16
learning_rate: 5.0e-07
lr_scheduler_type: cosine
warmup_ratio: 0.1
max_grad_norm: 1.0
lora_rank: 8
lora_target: all
val_size: 0.0
per_device_eval_batch_size: 4
eval_strategy: 'no'
logging_steps: 20
save_steps: 300
plot_loss: true
overwrite_output_dir: true
bf16: true
model_name_or_path: mistralai/Mistral-7B-Instruct-v0.2
trust_remote_code: true
cache_dir: ./cache/mistral-7b-it
dataset: ultra_paired_fb0.0167
output_dir: ./saves_mistral-7b-it/large_paired/nl1000
