bf16: true
cache_dir: ./cache
cutoff_len: 1024
dataset: ultra_combined_fb0.01_ch0.1
dataset_dir: src/data
do_train: true
eval_strategy: 'no'
finetuning_type: lora
gradient_accumulation_steps: 16
learning_rate: 1.0e-05
logging_steps: 10
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 50
model_name_or_path: ./cache/mistralai/Mistral-7B-Instruct-v0.2
num_train_epochs: 1
output_dir: ./saves_mistral-7b-it/sspo/fb0.01_gamma0.1_test
overwrite_cache: false
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 4
plot_loss: true
pref_beta: 2.0
pref_loss: sspo
preprocessing_num_workers: 8
report_to: none
save_steps: 100
sspo_gamma_0: 0.1
sspo_gamma_decay: 0.0
sspo_gamma_min: 0.1
sspo_prior: 0.5
stage: dpo
template: mistral
trust_remote_code: true
val_size: 0.0
warmup_ratio: 0.1
